const kurlyDB = [
    {   
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },{   
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },
    {
        src: './images/kurly_003.jpg',
        name: '[풀무원] 얇은피 꽉찬속 만두 고기맛',
        summary: '속이 꽉 찬 얇은피 만두',
        price:4980,
        sale:15,
        review:240,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[서울우유] 멸균우유 200ml x 24팩',
        summary: '언제 어디서나 간편하게 멸균우유',
        price:13200,
        sale:10,
        review:87,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[마켓컬리] 제철 과일 모음 박스',
        summary: '싱싱한 과일을 한 박스에',
        price:19800,
        sale:5,
        review:56,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[삼립] 소보로 단팥빵 5개입',
        summary: '달콤한 추억의 맛',
        price:3980,
        sale:12,
        review:134,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[청정원] 고소한 참기름 500ml',
        summary: '요리에 깊은 맛을 더하다',
        price:7200,
        sale:8,
        review:43,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[오뚜기] 3분 쇠고기 카레',
        summary: '빠르고 맛있는 한 끼',
        price:1980,
        sale:10,
        review:75,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[비비고] 사골곰탕 500g',
        summary: '진하고 깊은 국물 맛',
        price:3500,
        sale:18,
        review:210,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[햇반] 오곡밥 210g x 12개입',
        summary: '든든한 곡물밥으로 건강하게',
        price:11800,
        sale:13,
        review:92,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[하림] 닭가슴살 슬라이스 1kg',
        summary: '단백질이 풍부한 닭가슴살',
        price:11200,
        sale:25,
        review:167,
    }
];
